export const CardTypeEnum = {
  HIGH_CARD: 'HIGH_CARD',
  ONE_PAIRS: 'ONE_PAIRS',
  TWO_PAIRS: 'TWO_PAIRS',
  THREE_OF_A_KIND: 'THREE_OF_A_KIND',
  STRAIGHT: 'STRAIGHT',
  FLUSH: 'FLUSH',
  FULLHOUSE: 'FULLHOUSE',
  FOUR_OF_A_KIND: 'FOUR_OF_A_KIND',
  STRAIGHT_FLUSH: 'STRAIGHT_FLUSH',
  ROYAL_FLUSH: 'ROYAL_FLUSH',
};

export const StreetEnum = {
  PREFLOP: 'PREFLOP',
  FLOP: 'FLOP',
  TURN: 'TURN',
  RIVER: 'RIVER',
};
